P4ORCH_SHARED_SOURCES = \
	$(top_srcdir)/orchagent/orch.cpp \
	$(top_srcdir)/orchagent/vrforch.cpp \
	$(top_srcdir)/orchagent/vxlanorch.cpp \
	$(top_srcdir)/orchagent/copporch.cpp \
	$(top_srcdir)/orchagent/switch/switch_capabilities.cpp \
	$(top_srcdir)/orchagent/switch/switch_helper.cpp \
	$(top_srcdir)/orchagent/switch/trimming/capabilities.cpp \
	$(top_srcdir)/orchagent/switch/trimming/helper.cpp \
	$(top_srcdir)/orchagent/switchorch.cpp \
	$(top_srcdir)/orchagent/request_parser.cpp \
	$(top_srcdir)/lib/recorder.cpp \
	$(top_srcdir)/orchagent/zmqorch.cpp \
	$(top_srcdir)/orchagent/namelabelmapper.cpp \
	$(top_srcdir)/orchagent/flex_counter/flex_counter_manager.cpp \
	$(top_srcdir)/orchagent/flex_counter/flow_counter_handler.cpp \
	$(top_srcdir)/orchagent/port/port_capabilities.cpp \
	$(top_srcdir)/orchagent/port/porthlpr.cpp \
	$(top_srcdir)/orchagent/notifications.cpp \
	$(top_srcdir)/orchagent/p4orch/p4oidmapper.cpp \
	$(top_srcdir)/orchagent/p4orch/p4orch.cpp \
	$(top_srcdir)/orchagent/p4orch/p4orch_util.cpp \
	$(top_srcdir)/orchagent/p4orch/tables_definition_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/router_interface_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/gre_tunnel_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/neighbor_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/next_hop_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/route_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/acl_util.cpp \
	$(top_srcdir)/orchagent/p4orch/acl_table_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/acl_rule_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/wcmp_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/mirror_session_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/l3_admit_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/l3_multicast_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/tunnel_decap_group_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/ip_multicast_manager.cpp \
	$(top_srcdir)/orchagent/p4orch/ext_tables_manager.cpp
